name: CI-CD Blue Green Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: myapp
  CONTAINER_PORT: 5000

jobs:

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push \
            ${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}

  deploy:
    name: Blue Green Deployment
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |

            set -e

            echo "================================"
            echo "Starting Blue Green Deployment"
            echo "================================"

            AWS_REGION="ap-south-1"
            ECR_REPOSITORY="myapp"
            IMAGE_TAG="${{ github.sha }}"

            ACCOUNT_ID=$(aws sts get-caller-identity \
              --query Account \
              --output text)

            ECR_REGISTRY="${ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com"

            IMAGE="${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"

            echo "Image: $IMAGE"

            echo "Logging into ECR..."

            aws ecr get-login-password \
              --region $AWS_REGION | \
              docker login \
              --username AWS \
              --password-stdin $ECR_REGISTRY

            echo "Pulling new image..."

            docker pull $IMAGE

            echo "Checking current containers..."

            if docker ps --format '{{.Names}}' | grep -q '^myapp-blue$'; then

              CURRENT="blue"
              NEW="green"
              NEW_PORT="5002"

            else

              CURRENT="green"
              NEW="blue"
              NEW_PORT="5001"

            fi

            echo "Current environment: $CURRENT"
            echo "New environment: $NEW"
            echo "New port: $NEW_PORT"

            echo "Starting new container..."

            docker rm -f myapp-$NEW 2>/dev/null || true

            docker run -d \
              --name myapp-$NEW \
              --restart unless-stopped \
              -p $NEW_PORT:80 \
              $IMAGE

            echo "Waiting for application..."

            sleep 10

            echo "Testing new container..."

            curl -f http://127.0.0.1:$NEW_PORT/ || {
              echo "New container failed health check"
              docker logs myapp-$NEW
              exit 1
            }

            echo "New container is healthy"

            echo "Updating Nginx..."

            echo "Updating Nginx to $NEW..."

             sudo tee /etc/nginx/conf.d/myapp.conf > /dev/null <<EOF
             server {
                listen 80;

                location / {
                    proxy_pass http://127.0.0.1:$NEW_PORT;
                     proxy_set_header Host \$host;
                     proxy_set_header X-Real-IP \$remote_addr;
                     proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
                     proxy_set_header X-Forwarded-Proto \$scheme;
                  }
              }
              EOF

            echo "Testing Nginx configuration..."

            sudo nginx -t

            echo "Reloading Nginx..."

            sudo systemctl reload nginx

            echo "Stopping old container..."

            docker rm -f myapp-$CURRENT 2>/dev/null || true

            echo "================================"
            echo "Blue Green Deployment Successful"
            echo "Active environment: $NEW"
            echo "================================"
